Nurzed/Models/Plantao.cs
using MySql.Data.MySqlClient;
using System;

namespace Nurzed.Models
{
    public class Plantao
    {
        private string nome;
        private int numeroDoMes, qtdDias;
        static MySqlConnection con = new MySqlConnection(Conexao.conexaoString());

        public Plantao(string nome, int numeroDoMes, int qtdDias)
        {
            this.nome = nome;
            this.numeroDoMes = numeroDoMes;
            this.qtdDias = qtdDias;
        }

        public string Nome { get => nome; set => nome = value; }
        public int NumeroDoMes { get => numeroDoMes; set => numeroDoMes = value; }
        public int QtdDias { get => qtdDias; set => qtdDias = value; }


       


        }
    }

Nurzed/Controllers/AreaController.cs
using Microsoft.AspNetCore.Mvc;
using Nurzed.Models;

namespace Nurzed.Controllers
{
    public class AreaController : Controller
    {
        public IActionResult Cadastrar()
        {
            ViewData["listaArea"] = Area.Listar();
            return View();
        }

        [HttpPost]
        public IActionResult Cadastrar(string id, string nome, string status1)
        {
            Area area = new Area(id, nome, status1);
            
            TempData["msg"] = area.Cadastrar();
            if (TempData["msg"].ToString().Contains("Sucesso"))
            {
                return RedirectToAction("Cadastrar");
            }
            else
            {
                ViewData["listaArea"] = Area.Listar();
                return View();
            }
            
        }



        public IActionResult Listar()
        {
            return View(Area.Listar());
        }
    }
}

Nurzed/Controllers/EspecialidadeController.cs
using Microsoft.AspNetCore.Mvc;
using Nurzed.Models;

namespace Nurzed.Controllers
{
    public class EspecialidadeController : Controller
    {
        PadraoController padrao = new PadraoController();
        public IActionResult Cadastrar()
        {

            if (padrao.Logado(HttpContext) == true)
            {
                if (padrao.Privilegios(HttpContext) != "Administrador")
                {
                    return padrao.Home(HttpContext);
                }
                else
                {
                    ViewData["listaArea"] = Area.Listar();
                    ViewData["listaEspecialidade"] = Especialidade.Listar();
                    return View();
                }

            }
            else
            {
                return RedirectToAction("Login");
            }
          
        }
        [HttpPost]
        public IActionResult Cadastrar(string id,string nome,string nome_Area)
        {
            Especialidade especialidade = new Especialidade(id, nome,nome_Area);
            TempData["msg"] = especialidade.Cadastrar();
            if (especialidade.Cadastrar().Contains("Duplicate"))
            {
               

                return View();
            } else
            {
                return RedirectToAction("Cadastrar");
            }

        }



        public IActionResult Listar()
        {
            return View(Especialidade.Listar());
        }
    }
}

Nurzed/Controllers/PlantaoController.cs
using Microsoft.AspNetCore.Mvc;
using Nurzed.Models;

namespace Nurzed.Controllers
{
    public class PlantaoController : Controller
    {
        public IActionResult Plantao(string data1, string id_Cargo, string periodo, string id_Area)
        {                     

            ViewData["listaEnfermeiros"] = Usuarios.ListarUsuariosPlantao(data1,"5", periodo, "");
            ViewData["listaTecnicos"] = Usuarios.ListarUsuariosPlantao(data1, "1", periodo, "");
            ViewData["listaAux"] = Usuarios.ListarUsuariosPlantao(data1, "4", periodo, "");



            return View();
        }
    }
}

Nurzed/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using Nurzed.Models;

namespace Nurzed.Controllers
{
    public class UsuariosController : Controller
    {
        PadraoController padrao = new PadraoController();



        public IActionResult Login()
        {

            if (HttpContext.Session.GetString("usuarios") == null)
            {
                return View();
            }
            else
            {
                return RedirectToAction("HomeAdm");
            }

        }

        [HttpPost]
        public IActionResult Login(string cpf, string senha)
        {
            if (cpf != null && senha != null)
            {


                Usuarios u = new Usuarios("", "", "", padrao.Criptografar(senha), "", "", "", "", cpf, "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "");
                Usuarios usuarios = u.Verificar();


                if (usuarios != null)
                {

                    if (usuarios.Status1 == "ativado")
                    {
                        if (usuarios.Privilegios == "Administrador")
                        {
                            HttpContext.Session.SetString("usuarios", JsonConvert.SerializeObject(usuarios));
                            TempData["value"] = true;
                            return RedirectToAction("HomeAdm");
                        }
                        else if (usuarios.Privilegios == "Gestor")
                        {
                            HttpContext.Session.SetString("usuarios", JsonConvert.SerializeObject(usuarios));
                            TempData["value"] = true;
                            return RedirectToAction("HomeGestor");
                        }
                        else if (usuarios.Privilegios == "Comum")
                        {
                            HttpContext.Session.SetString("usuarios", JsonConvert.SerializeObject(usuarios));
                            TempData["value"] = true;
                            return RedirectToAction("HomeEnf");
                        }
                        else
                        {
                            TempData["msg"] = "Privilegio incorreto";
                            TempData["value"] = false;
                            return RedirectToAction("Login");
                        }


                    }
                    else
                    {
                        TempData["msg"] = "Sua conta está desativada, entre em contato com o Administrador";
                        TempData["value"] = false;
                        return RedirectToAction("Login");
                    }
                }
                else
                {
                    TempData["msg"] = "Usuário/Senha Incorreto(s)";
                    TempData["value"] = false;
                    return RedirectToAction("Login");
                }
            }
            else
            {

                TempData["msg"] = "Por favor, preencha os campos em branco";
                TempData["value"] = false;
                return RedirectToAction("Login");
            }

        }




        public IActionResult Cadastrar()
        {

            if (padrao.Logado(HttpContext) == true)
            {
                if (padrao.Privilegios(HttpContext) == "Administrador" || padrao.Privilegios(HttpContext) == "Gestor")
                {
                    ViewData["listaUniversidade"] = Universidade.Listar();
                    ViewData["listaCurso"] = Curso.Listar();
                    ViewData["listaEspecialidade"] = Especialidade.Listar();
                    ViewData["listaCargo"] = Cargo.Listar();
                    ViewData["listaArea"] = Area.Listar();

                    return View();
                }
                else
                {

                    TempData["msgPrivilegios"] = "Privilegios insuficientes";
                    return RedirectToAction("HomeEnf", "Usuarios");
                }
            }
            else
            {
                return RedirectToAction("Login");
            }

        }
        [HttpPost]
        public IActionResult Cadastrar(string id, string status1, string nome, string senha, string nome_da_mae, string nome_do_pai, string data_de_nascimento,
            string sexo, string cpf, string rg, string data_de_inicio_Universidade, string data_de_termino_Universidade, string coren, string cep, string telefone,
            string matricula, string Id_Especialidade, string Id_Cargo, string tipo_de_contrato, string data_de_criacao, string data_de_modificacao, string privilegios,
            string id_Universidade, string id_Curso, string id_Area, string periodo)
        {
            Usuarios u = padrao.RetornarObjeto(HttpContext);


            if (privilegios == "Administrador")
            {
                Usuarios usuarios = new Usuarios(id, status1, nome, padrao.Criptografar(senha), nome_da_mae, nome_do_pai, data_de_nascimento, sexo, cpf,
              rg, "", "", "", cep, telefone, "00000000000", "13", "3", "",
              data_de_criacao, data_de_modificacao, privilegios, "10", "8", "7", u.Nome, "");
                TempData["msg"] = usuarios.Cadastrar();


            }
            else
            {
                Usuarios usuarios = new Usuarios(id, status1, nome, padrao.Criptografar(senha), nome_da_mae, nome_do_pai, data_de_nascimento, sexo, cpf,
               rg, data_de_inicio_Universidade, data_de_termino_Universidade, coren, cep, telefone, matricula, Id_Especialidade, Id_Cargo, tipo_de_contrato,
               data_de_criacao, data_de_modificacao, privilegios, id_Universidade, id_Curso, id_Area, u.Nome, periodo);
                TempData["msg"] = usuarios.Cadastrar();
            }
            if (TempData["msg"].ToString().Contains("Sucesso"))
            {
                return RedirectToAction("Cadastrar");
            }
            else
            {
                ViewData["listaUniversidade"] = Universidade.Listar();
                ViewData["listaCurso"] = Curso.Listar();
                ViewData["listaEspecialidade"] = Especialidade.Listar();
                ViewData["listaCargo"] = Cargo.Listar();
                ViewData["listaArea"] = Area.Listar();
                return View();
            }


        }



        public IActionResult Listar()
        {
            if (padrao.Logado(HttpContext) == true)
            {
                if (padrao.Privilegios(HttpContext) != "Administrador")
                {
                    return padrao.Home(HttpContext);
                }
                else
                {

                    ViewData["listaUsuarios"] = Usuarios.Listar();
                    return View(Usuarios.Listar());
                }

            }
            else
            {
                return RedirectToAction("Login");
            }

            
        }


        public IActionResult Ativar(string cpf)
        {


            Usuarios usuarios = new Usuarios("", "", "", "", "", "", "", "", cpf, "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "");

            TempData["msgAtivar"] = usuarios.AtivarInativar("ativar");
            return RedirectToAction("Listar");


        }
        public IActionResult Inativar(string cpf)
        {
            Usuarios usuarios = new Usuarios("", "", "", "", "", "", "", "", cpf, "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "", "");

            TempData["msgInativar"] = usuarios.AtivarInativar("inativar");
            return RedirectToAction("Listar");
        }

        public IActionResult Editar(string id, string cpf, string especialidade, string cargo)
        {
            TempData["id"] = id;
            TempData["cpf"] = cpf;
            ViewData["listaUniversidade"] = Universidade.Listar();
            ViewData["listaCurso"] = Curso.Listar();
            ViewData["listaEspecialidade"] = Especialidade.Listar();
            ViewData["listaCargo"] = Cargo.Listar();
            ViewData["listaArea"] = Area.Listar();
            ViewData["dados"] = Usuarios.ListarDados(id);

            return View();
        }

        [HttpPost]
        public IActionResult Editar(string id, string status1, string nome, string senha, string nome_da_mae, string nome_do_pai,
            string data_de_nascimento, string sexo, string cpf, string rg, string data_de_inicio_Universidade, string data_de_termino_Universidade,
            string coren, string cep, string telefone, string matricula, string Id_Especialidade, string Id_Cargo, string tipo_de_contrato,
            string data_de_criacao, string data_de_modificacao, string privilegios, string id_Universidade, string id_Curso, string id_Area, string periodo)
        {
            Usuarios u = padrao.RetornarObjeto(HttpContext);
            Usuarios usuarios = new Usuarios(id, status1, nome, senha, nome_da_mae, nome_do_pai, data_de_nascimento, sexo, cpf, rg, data_de_inicio_Universidade,
                data_de_termino_Universidade, coren, cep, telefone, matricula, Id_Especialidade, Id_Cargo, tipo_de_contrato, data_de_criacao, data_de_modificacao,
                privilegios, id_Universidade, id_Curso, id_Area, u.Nome, periodo);

            TempData["id"] = id;
            TempData["msgEditar"] = usuarios.Editar(id);

            return RedirectToAction("Listar");

        }


        public IActionResult Sair()
        {
            HttpContext.Session.Remove("usuarios");
            return RedirectToAction("Login");
        }






        public IActionResult HomeAdm()
        {
           

            if (padrao.Logado(HttpContext) == true)
            {
                if(padrao.Privilegios(HttpContext) != "Administrador")
                {
                    return padrao.Home(HttpContext);
                }
                else
                {
                    return View();
                }

Nurzed/Views/Usuarios/Cadastrar.cshtml
@using Microsoft.AspNetCore.Http;
@using Newtonsoft.Json;
@model Nurzed.Models.Usuarios
@{
    ViewData["Title"] = "Cadastrar";
    IEnumerable<Universidade> listaUniversidade = ViewData["listaUniversidade"] as IEnumerable<Universidade>;
    IEnumerable<Curso> listaCurso = ViewData["listaCurso"] as IEnumerable<Curso>;
    IEnumerable<Especialidade> listaEspecialidade = ViewData["listaEspecialidade"] as IEnumerable<Especialidade>;
    IEnumerable<Cargo> listaCargo = ViewData["listaCargo"] as IEnumerable<Cargo>;
    IEnumerable<Area> listaArea = ViewData["listaArea"] as IEnumerable<Area>;

    Usuarios u = JsonConvert.DeserializeObject<Usuarios>(Context.Session.GetString("usuarios"));
    
}
<partial name="_Toast" />
<link rel="stylesheet" href="~/css/cadastro.css">



<div class="contaner_titulo_index">
    <a asp-action="Voltar">
        <button class="btn_voltar_adm">
            <img src="~/img/voltar.png" alt="" class="img_btn_voltar">
        </button>
    </a>
</div>

<h1 class="titulo_pagina_adm">Adicionar usuário</h1>

<form asp-action="Cadastrar">
    <div id="area_selecao_user">
        <h3>Que tipo de usúario deseja adicionar ? </h3>

        
            <div class="opicao_area_selecao_user">
                <input type="radio" name="privilegios" checked value="Comum"
                   class="radio_opicao_area_selecao_user" onclick="escolherTipoUsuario(this)">
                <p>Usuário Comum</p>
            </div>
        @if (u.Privilegios == "Administrador")
        {
            <div class="opicao_area_selecao_user">
                <input type="radio" name="privilegios" value="Gestor"
                   class="radio_opicao_area_selecao_user" onclick="escolherTipoUsuario(this)">
                <p>Usuário Gestor</p>
            </div>

            <div class="opicao_area_selecao_user">
                <input type="radio" name="privilegios" value="Administrador"
                   class="radio_opicao_area_selecao_user" onclick="escolherTipoUsuario(this)">
            <p>Usuário Administrador</p>
        </div>
        }
    </div>

    <section id="sec_cadastro">
        <Label class="label_cadastro">Nome Completo: </Label><sup class="asteritico">*</sup><br>
        <input type="text" name="nome" id="nomecompleto" class="caixa_texto" minlength="2" maxlength="100"   ><br>

        <Label class="label_cadastro">Nome da mãe: </Label><sup class="asteritico">*</sup><br>
        <input type="text" name="nome_da_mae" id="nomemae" class="caixa_texto"
               minlength="2" maxlength="100"><br>


        <Label class="label_cadastro">Nome do pai: </Label><br>
        <input type="text" name="nome_do_pai" id="nomepai" class="caixa_texto"
               minlength="2" maxlength="100" >

        <div class="input2">
            <div id="auxCamila">
                <Label class="label_cadastro">Data de nascimento: </Label><sup class="asteritico">*</sup><br>
                <input type="text" name="data_de_nascimento" id="data_nascimento"
                       class="caixa_texto_mini">
            </div>

            <div>
                <Label class="label_cadastro">CPF: </Label><sup class="asteritico">*</sup><br>
                <input type="text" name="cpf" id="cpf" class="caixa_texto_mini"
                       minlength="14" maxlength="14">
            </div>
        </div>

        <div class="input2">
            <div id="auxCamila">
                <Label class="label_cadastro">Sexo: </Label><sup class="asteritico">*</sup><br>
                <select id="sexo" name="sexo" class="caixa_texto" style="margin: 10px 30px 0 0; width: 415px;">
                    <option value="Masculino">Masculino</option>
                    <option value="Feminino">Feminino</option>
                </select>
            </div>

            <div>
                <Label class="label_cadastro">RG: </Label><sup class="asteritico">*</sup><br>
                <input type="text" name="rg" id="rg" class="caixa_texto_mini" minlength="12"
                       maxlength="12">
            </div>
        </div>

        <div class="input2">
            <div id="auxCamila">
                <Label class="label_cadastro">CEP: </Label><sup class="asteritico">*</sup><br>
                <input type="text" name="cep" id="cep" class="caixa_texto_mini" minlength="9"
                       maxlength="9">
            </div>

            <div>
                <Label class="label_cadastro">Telefone: </Label><sup class="asteritico">*</sup><br>
                <input type="text" name="telefone" id="telefone" class="caixa_texto_mini"
                       minlength="14" maxlength="14">
            </div>
        </div>

        <div id="div_dadosHospitalares">
        <hr class="linha_cadastro">

        <Label class="label_cadastro"> Curso:</Label><sup class="asteritico">*</sup><br>
        <select class="caixa_texto" name="id_Curso">

            @foreach (var item in listaCurso)
            {
                <option value="@item.Id">@item.Nome </option>
            }
        </select>
        <br>

        <Label class="label_cadastro">Universidade:</Label><sup class="asteritico">*</sup><br>
        <select class="caixa_texto" name="id_Universidade">

            @foreach (var item in listaUniversidade)
            {
                <option value="@item.Id">@item.Nome (@item.Sigla) </option>
            }
        </select>
        <br>

        <div class="input2">
            <div id="auxCamila">
                <Label class="label_cadastro">Data de início universidade: </Label><sup class="asteritico">*</sup><br>
                <input type="text" name="data_de_inicio_Universidade" id="uni_inicio" class="caixa_texto_mini"
                       minlength="8">
            </div>

            <div>
                <Label class="label_cadastro">Data término universidade: </Label><sup class="asteritico">*</sup><br>
                <input type="text" name="data_de_termino_Universidade" id="uni_fim" class="caixa_texto_mini">
            </div>
        </div>

        <hr class="linha_cadastro">

        <Label class="label_cadastro">Cargo:</Label><sup class="asteritico">*</sup><br>
        <select class="caixa_texto" name="id_Cargo">

            @foreach (var item in listaCargo)
            {
                <option value="@item.Id">@item.Nome </option>
            }
        </select>
        <br>

        <Label class="label_cadastro">Área:</Label><sup class="asteritico">*</sup><br>
        <select class="caixa_texto" name="id_Area">

            @foreach (var item in listaArea)
            {
                <option value="@item.Id">@item.Nome </option>
            }
        </select>
        <br>

        <Label class="label_cadastro">Especialidade:</Label><sup class="asteritico">*</sup><br>
        <select class="caixa_texto" name="id_Especialidade">

            @foreach (var item in listaEspecialidade)
            {
                <option value="@item.Id">@item.Nome </option>
            }
        </select>
        <br>

        <Label class="label_cadastro">Periodo:</Label><sup class="asteritico">*</sup><br>
        <select class="caixa_texto" name="periodo">
            <option asp-for="Tipo_de_contrato" value="manha">Manhã</option>
            <option asp-for="Tipo_de_contrato" value="tarde">Tarde</option>
            <option asp-for="Tipo_de_contrato" value="noite">Noite</option>
        </select>
        <br>

        <Label class="label_cadastro">Tipo de contrato:</Label><sup class="asteritico">*</sup><br>
        <select class="caixa_texto" name="tipo_de_contrato">
            <option value="Concursado">Concursado</option>
            <option value="Terceirizado">Terceirizado</option>
        </select>
        <br>

        <div class="input2">
            <div id="auxCamila">
                <Label class="label_cadastro">COREN: </Label><sup class="asteritico">*</sup><br>
                <input type="text" name="coren" id="coren" class="caixa_texto_mini" minlength="2" maxlength="250">
            </div>

            <div>
                <Label class="label_cadastro">Matrícula: </Label><sup class="asteritico">*</sup><br>
                <input type="text" name="matricula" id="matricula" class="caixa_texto_mini" minlength="8"
                       maxlength="8">
            </div>
        </div>
        </div>
        <div class="input2">
            <div id="auxCamila">
                <Label class="label_cadastro">Senha: </Label><sup class="asteritico">*</sup><br>
                <input type="password" name="senha" id="senha" class="caixa_texto_mini" minlength="8" maxlength="40">
            </div>

        </div>

    </section>

    <div id="btn_final_cadastro_adm">
        <button class="btn_Finalizar_adm" onclick="ValidacaoGeral() " type="submit">Finalizar</button>
        <br>
    </div>
</form>





<script src="~/js/valida_forms.js"></script>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<script src="~/js/jquery.mask.js"></script>


<script>
    $(document).ready(function() {
        $('#rg').mask('00.000.000-00');
        $('#cep').mask('00000-000');
        $('#cpf').mask('000.000.000-00')
        $('#telefone').mask('(00) 00000-0000')
        $('#coren').mask('COREN-AA 000.000-AAAA')
        $('#data_nascimento').mask('00/00/0000')
        $('#uni_inicio').mask('00/00/0000')
        $('#uni_fim').mask('00/00/0000')
    })
</script>

Nurzed/Views/Usuarios/HomeAdm.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@{
    Usuarios u = JsonConvert.DeserializeObject<Usuarios>(Context.Session.GetString("usuarios"));
}    

    <link rel="stylesheet" href="~/css/homes.css">
    

    


        <div class="container_home">
        <br><br><br><p id="area_trab_adm">Área de trabalho:@u.Id_Area</p>

        <div class="container_home_btn">
            <a asp-controller="Usuarios" asp-action="Plantao"><button class="btn_acoens_home_adm" <img src="~/img/calendario_adm.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_adm">Ver Plantão</p></button></a>
            <a asp-controller="Especialidade" asp-action="Cadastrar"><button class="btn_acoens_home_adm" ><img src="~/img/adm_add.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_adm">Adicionar Especialidades</p></button></a>
            
        </div>

        <div class="container_home_btn">
            <a asp-controller="Usuarios" asp-action="Cadastrar"><button class="btn_acoens_home_adm"><img src="~/img/adm_add4.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_adm">Adicionar Usuário</p></button></a>
            <a asp-controller="Cronograma" asp-action="Cadastrar"><button class="btn_acoens_home_adm"><img src="~/img/Historico_adm.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_adm">Adicionar Cronograma</p></button></a>
        </div>

        <div class="container_home_btn">
            <a asp-controller="Area" asp-action="Cadastrar"><button class="btn_acoens_home_adm"><img src="~/img/adm_add3.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_adm">Adicionar Áreas</p></button></a>
            <a asp-controller="Usuarios" asp-action="Listar"><button class="btn_acoens_home_adm"><img src="~/img/dados_user.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_adm">Dados dos users</p></button></a>
        </div>

    </div>


    <p id="nome_rodape">@u.Nome</p>

Nurzed/Views/Usuarios/HomeEnf.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@{
    Usuarios u = JsonConvert.DeserializeObject<Usuarios>(Context.Session.GetString("usuarios"));
}

<link rel="stylesheet" href="~/css/homes.css">





<div class="container_home">
    <br><br><br><p id="area_trab_adm">Área de trabalho:@u.Id_Area</p>

    <div class="container_home_btn">
        <a asp-controller="Usuarios" asp-action="Plantao"><button class="btn_acoens_home_adm" <img src="~/img/calendario_adm.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_adm">Ver Plantão</p></button></a>
        

    </div>

  

</div>


<p id="nome_rodape">@u.Nome</p>

Nurzed/Views/Usuarios/HomeGestor.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json
@{
    Usuarios u = JsonConvert.DeserializeObject<Usuarios>(Context.Session.GetString("usuarios"));
}    

    <link rel="stylesheet" href="~/css/homes.css"> 

<div class="container_home">
        <br><br><br>
        <div class="container_area_de_trabalho">          
            <p id="area_trab_gest">Área de trabalho:@u.Id_Area</p>
        </div>

        <div class="container_home_btn">
           <a asp-controller="Usuarios" asp-action="Plantao"> <button class="btn_acoens_home_gest"><img src="~/img/calendario_gest.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_gest">Ver plantão</p></button></a>
           <a asp-controller="Cronograma" asp-action="Cadastrar"><button class="btn_acoens_home_gest"><img src="~/img/Historico_gest.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_gest">Add cronograma</p></button></a>
        </div>

        <div class="container_home_btn">
            <a asp-controller="Usuarios" asp-action="Cadastrar"> <button class="btn_acoens_home_gest"><img src="~/img/gest_add.png" class="img_btn_home_enf" alt=""> <p class="texto_btn_gest">Adicionar enfermeiro</p></button></a>
        </div>
    </div>

    <p id="nome_rodape_gest">@u.Nome</p>

Nurzed/Views/Usuarios/Listar.cshtml
@{
    ViewData["Title"] = "Dados do usuário";

    IEnumerable<Usuarios> listaUsuarios = ViewData["listaUsuarios"] as IEnumerable<Usuarios>;
}



<link rel="stylesheet" href="~/css/dados.css">
<script src="https://code.jquery.com/jquery-3.1.1.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.quicksearch/2.3.1/jquery.quicksearch.js"></script>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">






<div class="contaner_titulo_index">
    <a asp-action="Voltar">
        <button class="btn_voltar_adm">
            <img src="~/img/voltar.png" alt="" class="img_btn_voltar">
        </button>
    </a>
</div>
<h1 class="titulo_pagina_adm">Dados do usuário</h1>


<section>
    <div class="form-group input-group" id="div-group-tabela">

        <div id="aux4">
            <input name="consulta" id="pesquisa_cpf" placeholder="Consultar CPF" type="text" class="form-control"> <img src="~/img/lupa.png" id="lupa" alt="" minlength="4" maxlength="250" required>
        </div>
    </div>
    <table class="table" id="tabela">

        <tbody>
            @foreach (var item in listaUsuarios)
            {
                <tr>

                    <td id="td">
                        <div class="container_dados">

                            <img src="~/img/dados_user.png" alt="" class="img_user_dados">
                            <div class="texto_dados">
                                <p class="texto_dados_nome">@item.Nome</p>
                                <p class="texto_dados_pessoais">@item.Cpf</p>
                                <p class="texto_dados_pessoais">@item.Id_Cargo</p>
                                <p class="texto_dados_pessoais">@item.Id_Area</p>
                            </div>
                            <div class="margin_btns">
                            <button class="btn_editar_dados">@Html.ActionLink("Editar", "Editar", new { id = item.Id, cpf = item.Cpf, especialidade = item.Id_Especialidade, cargo = item.Id_Cargo})</button>
                            @if (@item.Status1 == "ativado")
                            {
                                <button class="btn_editar_dados btn_inativar">@Html.ActionLink("Inativar", "Inativar", new { cpf = item.Cpf })</button>
                            }
                            else
                            {
                                <button class="btn_editar_dados btn_ativar">@Html.ActionLink("Ativar", "Ativar", new { cpf = item.Cpf })</button>
                            }
                        </div>
                        </div>
                    </td>
                </tr>
            }

        </tbody>

</section>





<script>
    $('input#pesquisa_cpf').quicksearch('table#tabela tbody tr');
</script>
</html>